### ISSUE TITLE
Set up CI with GitHub Actions

### ISSUE THREAD

**Issue by RalphORama** [RalphORama/keystone-react#3]
Write a CI workflow that will install Yarn, then run `yarn install` and `yarn test`.

**Comment by sowmiyamuthuraman** [comment]
Can I work on this?

**Comment by RalphORama** [comment]
@sowmiyamuthuraman sure thing, just fork and submit a PR

**Comment by RalphORama** [comment]
@sowmiyamuthuraman sure thing, just fork and submit a PR
